const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.video,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.SetTweensEase,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.X
	];
};
self.C3_JsPropNameTable = [
	{Home: 0},
	{HomeV: 0},
	{Difficulty: 0},
	{DifficultyV: 0},
	{Chapter: 0},
	{ChapterV: 0},
	{Levels: 0},
	{LevelsV: 0},
	{Soal: 0},
	{SoalV: 0},
	{Results: 0},
	{ResultsV: 0},
	{Tween: 0},
	{start_btn: 0},
	{exit_btn: 0},
	{SD_btn: 0},
	{SMP_btn: 0},
	{back: 0},
	{Right_btn: 0},
	{Left_btn: 0},
	{mtk_btn: 0},
	{inggris_btn: 0},
	{negara_btn: 0},
	{sejarah_btn: 0},
	{level1: 0},
	{level2: 0},
	{level3: 0},
	{a_btn: 0},
	{b_btn: 0},
	{d_btn: 0},
	{c_btn: 0},
	{restart_btn: 0},
	{home_btn: 0},
	{Soal_MTKSD: 0},
	{correct: 0},
	{wrong: 0},
	{Browser: 0},
	{Touch: 0},
	{Audio: 0},
	{star: 0},
	{star2: 0},
	{star3: 0},
	{Medal: 0},
	{ScoreBenar: 0},
	{ScoreSalah: 0},
	{Trophy: 0},
	{t: 0},
	{debug: 0},
	{Terjawab: 0},
	{MTKLevelSD: 0},
	{MTKLevelSMP: 0},
	{MTKSMP_Medals: 0},
	{MTKSD_Medals: 0},
	{INGGRISSMP_Medals: 0},
	{INGGRISSD_Medals: 0},
	{NEGARASMP_Medals: 0},
	{NEGARASD_Medals: 0},
	{SEJARAHSMP_Medals: 0},
	{SEJARAHSD_Medals: 0},
	{INGGRISLevelSD: 0},
	{INGGRISLevelSMP: 0},
	{NEGARALevelSD: 0},
	{NEGARALevelSMP: 0},
	{SEJARAHLevelSD: 0},
	{SEJARAHLevelSMP: 0},
	{Diffuculty: 0},
	{Score: 0},
	{Incorrect: 0},
	{Mapel: 0}
];

self.InstanceType = {
	Home: class extends self.ISpriteInstance {},
	HomeV: class extends self.IWorldInstance {},
	Difficulty: class extends self.ISpriteInstance {},
	DifficultyV: class extends self.IWorldInstance {},
	Chapter: class extends self.ISpriteInstance {},
	ChapterV: class extends self.IWorldInstance {},
	Levels: class extends self.ISpriteInstance {},
	LevelsV: class extends self.IWorldInstance {},
	Soal: class extends self.ISpriteInstance {},
	SoalV: class extends self.IWorldInstance {},
	Results: class extends self.ISpriteInstance {},
	ResultsV: class extends self.IWorldInstance {},
	start_btn: class extends self.ISpriteInstance {},
	exit_btn: class extends self.ISpriteInstance {},
	SD_btn: class extends self.ISpriteInstance {},
	SMP_btn: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	Right_btn: class extends self.ISpriteInstance {},
	Left_btn: class extends self.ISpriteInstance {},
	mtk_btn: class extends self.ISpriteInstance {},
	inggris_btn: class extends self.ISpriteInstance {},
	negara_btn: class extends self.ISpriteInstance {},
	sejarah_btn: class extends self.ISpriteInstance {},
	level1: class extends self.ISpriteInstance {},
	level2: class extends self.ISpriteInstance {},
	level3: class extends self.ISpriteInstance {},
	a_btn: class extends self.ISpriteInstance {},
	b_btn: class extends self.ISpriteInstance {},
	d_btn: class extends self.ISpriteInstance {},
	c_btn: class extends self.ISpriteInstance {},
	restart_btn: class extends self.ISpriteInstance {},
	home_btn: class extends self.ISpriteInstance {},
	Soal_MTKSD: class extends self.ITextInstance {},
	correct: class extends self.ISpriteInstance {},
	wrong: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	star: class extends self.ISpriteInstance {},
	star2: class extends self.ISpriteInstance {},
	star3: class extends self.ISpriteInstance {},
	Medal: class extends self.ISpriteInstance {},
	ScoreBenar: class extends self.ITextInstance {},
	ScoreSalah: class extends self.ITextInstance {},
	Trophy: class extends self.ITextInstance {},
	t: class extends self.ITextInstance {},
	debug: class extends self.ISpriteInstance {}
}